### ISSUE TITLE
[Suggestions] Five suggestions for the mod

### ISSUE THREAD

**Issue by DeleteMetaInf** [castcrafter/travel_anchors#58] opened 2022-08-31 09:27 UTC
I love the mod and am ecstatic that someone ported what is arguably the second best feature from Ender IO (the first obviously being conduits). I just have a few suggestions that I think would make the mod even better if implemented!

1. The ability to disguise the travel anchor as another block. This was possible in Ender IO using the painting machine. It’d be nice if you could craft the travel anchor with any block, or sneak-right-click it whilst holding any block, to disguise it as that block. Would make it a lot more aesthetically pleasing.

2. This has been suggested in #33 and #43, but I just want to say that I, too, would love the ability to associate a specific travel anchor with a block or item rather than a name to make the screen less cluttered and allow you to find certain travel anchors faster.

3. Change the text colour of a travel anchor. It’d help you find certain travel anchors, and help organize the screen a little bit, by allowing you to change the colour of a travel anchor’s text, perhaps being able to select between any of Minecraft’s sixteen default colours. Would be useful for sure!

4. With a travel anchor on the same Y level as another, you can teleport to the one above it, regardless of blocks in the way, by jumping, but you can’t teleport to the one below it. It’d be nice if you could teleport to a travel anchor below another one by sneaking on top of a travel anchor, similar to how the elevator from [OpenBlocks Elevator](https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator) works. This would allow the travel anchor to double as an elevator and a standard travel anchor.

5. A config option to increase the range of the sneak-right-click functionality that allows you to teleport through walls. I find that I often either don’t teleport at all or teleport up to the wall and not through it. It’d be nice to have a config option that allows you to increase the range at which you can teleport through a wall/floor/ceiling.

**Comment by florian-berger** [comment] 2022-09-05 18:19
For 1, put the block you want to use into your off-hand, empty the main hand and right-click the travel anchor. The anchor now mimics this block.

**Comment by noeppi-noeppi** [comment] 2022-10-30 18:14
4. Should already be possible. Might be disabled in your client config though. Maybe take a look there: `config/travel_anchors/client.json5`

**Comment by noeppi-noeppi** [comment] 2022-11-01 10:21
5: has been added.

  3: Won't be implemented as the colour is used to highlight which anchor the player is about to teleport to.

This only leaves 2. which is a duplicate of #33, so I'm going to close this issue now.

**Closed by noeppi-noeppi** 2022-11-01 10:21 UTC
Labels: enhancement
